name: Untref tests

on:
    push:
        branches:
            - master
            - main
    pull_request:
        branches:
            - master
            - main

jobs:
    selenium-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
               python-version: '3.12.6'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install selenium python-dotenv requests html-testRunner unittest-xml-reporting

            - name: Install Webdriver Manager
                run: pip install webdriver-manager


            #- name: Set environment variables
              #run: echo "WEB_DATA=${{ secrets.WEB_DATA}}" >> $GITHUB_ENV

            - name: Run Selenium tests
              run: |
                python html_runner.py

            - name: Upload test report
              uses: actions/upload-artifact@v4
              with:
                  name: test-report
                  path: test-reports/
